version: '3'

services:

  api:
    build: ./api
    image: inadvertance/baby-foot-api
    volumes:
      - ./api/src:/code/src
    links:
      - db
    ports:
      - "$API_PORT:$API_PORT"
    environment:
      - PORT=$API_PORT
      - DB_HOST=db
      - DB_PORT=8529
  
  db:
    image: arangodb
    # volumes:
    ports:
      - "$DB_PORT:8529"
    environment:
      - ARANGO_NO_AUTH=1
