version: '3'

services:
  api:
    command: dev
    volumes:
      - ./src:/code/src
    ports:
      - "4000:4000"
    links:
      - db
    environment:
      PORT: 4000
      DB_URL: http://db:27017/baby-foot-dev

  db:
    image: arangodb/arangodb:3.7.2
    environment:
      ARANGO_NO_AUTH: 1
    ports:
      - "8529:8529"
