version: '3.8'

services:
  api:
    build: .
    image: inadvertance/baby-foot-api
    command: start
    ports:
      - "9000:9000"
    links:
      - db
    environment:
      PORT: 9000
      DB_URL: http://db:8529/baby-foot-dev
      REDIS_URI: redis://redis:6379

  ranking:
    build: .
    image: inadvertance/baby-foot-api-ranking-job
    command: jobs:ranking
    environment:
      REDIS_URI: redis://redis:6379

  db:
    image: arangodb/arangodb:3.7.2
    environment:
      ARANGO_NO_AUTH: 1
    ports:
      - "8529:8529"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
