version: '3'

services:
  api:
    command: test:api
    volumes:
      - ./src:/code/src
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      PORT: 3000
      DB_URL: http://db:27017/baby-foot-test

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
