version: '3'

services:
  api:
    command: test:watch
    volumes:
      - ./src:/code/src
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - PORT=3000
      - DB_URL=http://test:test@db:8529
      - DB_DATABASE=BabyFootTestDb

  db:
    image: arangodb:latest
    ports:
      - "8529:8529"
    environment:
      - ARANGO_NO_AUTH=1
