openapi: 3.0.0
info:
  title: Baby foot
  version: '1.0'
  contact:
    name: Andrea Gueugnaut
    email: gue@octo.com
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/matches:
    get:
      summary: List matches
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
      operationId: get-matches
    parameters: []
    post:
      summary: Create a match
      operationId: post-v1-matches
      responses:
        '201':
          description: Created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                red:
                  type: object
                  properties:
                    points:
                      type: integer
                      minimum: 0
                      maximum: 10
                    players:
                      type: array
                      minItems: 1
                      maxItems: 2
                      uniqueItems: true
                      items:
                        type: string
                blue:
                  type: object
                  properties:
                    points:
                      type: integer
                      minimum: 0
                      maximum: 10
                    players:
                      type: array
                      uniqueItems: true
                      minItems: 1
                      maxItems: 2
                      items:
                        type: string
components:
  schemas:
    Match:
      title: Match
      type: object
      x-tags:
        - Match
      properties:
        id:
          type: string
        red:
          $ref: '#/components/schemas/Team'
        blue:
          $ref: '#/components/schemas/Team'
        playedAt:
          $ref: '#/components/schemas/DateTime'
        createdAt:
          $ref: '#/components/schemas/DateTime'
        updatedAt:
          $ref: '#/components/schemas/DateTime'
    Team:
      title: Team
      type: object
      x-tags:
        - Team
      properties:
        id:
          type: string
        points:
          type: integer
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
        createdAt:
          $ref: '#/components/schemas/DateTime'
        updatedAt:
          $ref: '#/components/schemas/DateTime'
    Player:
      title: Player
      type: object
      x-tags:
        - Player
      properties:
        id:
          type: string
        createdAt:
          $ref: '#/components/schemas/DateTime'
        updatedAt:
          $ref: '#/components/schemas/DateTime'
    DateTime:
      type: string
      title: DateTime
      format: date-time
