swagger: '2.0'
info:
  version: '0.0.1'
  title: OCTO's baby-foot API
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  $ref: ./paths/index.yml
definitions:
  $ref: ./definitions/index.yml
parameters:
  $ref: ./parameters/index.yml
responses:
  $ref: ./responses/index.yml
