openapi: '3.0.0'
info:
  title: OCTO's baby-foot API
  description: Lorem ipsum dolor sit amet
  termsOfService: http://lorem-ipsum.sit
  contact:
    name: Andrea GUEUGNAUT
    url: https://falinor.github.io/baby-foot-api
    email: andrea.gueugnaut@gmail.com
  license:
    name: Apache 2.0 ??
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '0.0.0'
servers:
  - url: https://dev.falinor.com/{apiVersion}
    description: The development API server
    variables:
      apiVersion:
        default: v1
        description: |
          The API version. Atmost two API versions should be live at
          the same time.

components:
  headers:
    Accept:
      $ref: './components/headers.yml#/Accept'
    Content-Type:
      $ref: './components/headers.yml#/Content-Type'
  parameters:
    skip:
      $ref: './components/parameters.yml#/skip'
    limit:
      $ref: './components/parameters.yml#/limit'
  schemas:
    Match:
      $ref: './components/schemas/match.yml'
    Matches:
      $ref: './components/schemas/matches.yml'
    Player:
      $ref: './components/schemas/player.yml'
    Players:
      $ref: './components/schemas/players.yml'

paths:
  /matches:
    $ref: './paths/match/matches.yml'
  /players:
    $ref: './paths/player/players.yml'
  /players/{id}:
    $ref: './paths/player/player.yml'
# security:
# tags:
